// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChJwSVPwabyBH2oBnlTZHUIG7qzZkKeZY',
    appId: '1:768887897991:web:b11338f1052f58056d1d22',
    messagingSenderId: '768887897991',
    projectId: 'todo-71f52',
    authDomain: 'todo-71f52.firebaseapp.com',
    storageBucket: 'todo-71f52.firebasestorage.app',
    measurementId: 'G-J747ZSE8ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPFSEynvJgCgApXUX70r_9jQiEY1lesFA',
    appId: '1:768887897991:android:0e4e847c8e629b736d1d22',
    messagingSenderId: '768887897991',
    projectId: 'todo-71f52',
    storageBucket: 'todo-71f52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjEY9MPxT6Ic19SxwlRwFFVgwhD3h2Pas',
    appId: '1:768887897991:ios:0898bf97bee84a1c6d1d22',
    messagingSenderId: '768887897991',
    projectId: 'todo-71f52',
    storageBucket: 'todo-71f52.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjEY9MPxT6Ic19SxwlRwFFVgwhD3h2Pas',
    appId: '1:768887897991:ios:0898bf97bee84a1c6d1d22',
    messagingSenderId: '768887897991',
    projectId: 'todo-71f52',
    storageBucket: 'todo-71f52.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChJwSVPwabyBH2oBnlTZHUIG7qzZkKeZY',
    appId: '1:768887897991:web:06a667fb681d24536d1d22',
    messagingSenderId: '768887897991',
    projectId: 'todo-71f52',
    authDomain: 'todo-71f52.firebaseapp.com',
    storageBucket: 'todo-71f52.firebasestorage.app',
    measurementId: 'G-0Y4ZF7Y5MC',
  );
}
